version: '3.8'

services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_DATABASE: NewsApp_DB
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=NewsApp_DB
      - DB_USER=root
      - DB_PASS=
    depends_on:
      db:
        condition: service_healthy